name: Application Pipeline

on:
  push:
    branches:
      - main

jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          terraform init

      - name: Apply Terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          terraform apply -auto-approve -var github_token=$GITHUB_TOKEN -var github_username=$GITHUB_USERNAME

  setup-repos:
    needs: create-repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: source-org/source-repo
          path: source-code

      - name: Set Up Git
        run: |
          git config --global user.email "gogireddy.gayathri2002@gmail.com"
          git config --global user.name "Gayathri-Gogireddy"
          
      - name: Initialize Repos JSON
        run: |
          echo "[]" > repos.json
          
      - name: Process Applications
        run: |
          echo "${{ toJSON(steps.create-repos.outputs.repos) }}" > repos.json
          
          apps=$(jq -c '.[]' repos.json)
          for app in $apps; do
            app_name=$(echo $app | jq -r '.name')
            app_description=$(echo $app | jq -r '.description')
            
            # Clone the newly created repo
            git clone https://github.com/${{ github.repository_owner }}/${app_name}.git
            cd ${app_name}
            
            # Copy source code
            cp -r ../source-code/* .

            # Update GitHub Actions workflow
            sed -i "s/OLD_VARIABLE_NAME/${app_name}/g" .github/workflows/deploy.yml

            # Update terraform.tfvars
            sed -i "s/OLD_VAR1/NEW_VAR1/g" terraform.tfvars
            sed -i "s/OLD_VAR2/NEW_VAR2/g" terraform.tfvars

            # Commit and push changes
            git add .
            git commit -m "Configured for ${app_name}"
            git push origin main

            cd ..
          done
